### PR TITLE
fix: parse Mastodon handles correctly for canonical profile URLs

### LINKED ISSUE #2009: 🐛 Bug: Mastodon ambassador links break due to hard-coded server
### Problem
In `AmbassadorsCard.tsx`, Mastodon profile URLs are constructed by
hard-coding the server as `https://fosstodon.org/`.

However, the ambassador data already contains full Mastodon handles in
the standard format `@username@server`
(e.g. `@DavidBiesack@fosstodon.org`).

As a result, the generated link becomes:
`https://fosstodon.org/@DavidBiesack@fosstodon.org`,
which duplicates the server portion in the path.

While this may still resolve in some cases due to Mastodon server
tolerance, the URL construction is non-canonical and relies on
implementation-specific behavior rather than the standard Mastodon
profile URL format.

### Expected behavior
Mastodon handles should be parsed according to the standard
`@username@server` format and converted into a canonical profile URL of
the form `https://server/@username`.

### Additional context
The current Cypress test in `AmbassadorsCard.cy.tsx` appears to assert
this non-canonical URL format, which effectively locks in the incorrect
behavior and would need to be updated alongside the fix.
### Steps To Reproduce

1. Go to the Ambassadors section on the website.
2. Find an ambassador with a Mastodon handle that includes a server
   (e.g. `@DavidBiesack@fosstodon.org`).
3. Click the Mastodon icon/link on the ambassador card.
4. Observe that the generated URL is
   `https://fosstodon.org/@DavidBiesack@fosstodon.org`,
   which duplicates the server name in the path.

### Expected Behavior

The Mastodon link should be constructed according to the standard
handle format `@username@server`, resulting in a canonical profile URL
of the form `https://server/@username`.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by me-pradeep**
**What kind of change does this PR introduce?**
- Bugfix

**Issue Number:**
- Closes #2009

**Screenshots/videos:**
Previously, Mastodon profile links were constructed incorrectly, resulting in duplicated server names and broken redirects.  
This PR ensures profiles now correctly resolve to the canonical Mastodon URL format.

Fixed Mastodon profile URL behavior

**Summary**
- Parse `@username@server` format from ambassador data
- Construct canonical Mastodon profile URLs as `https://server/@username`
- Fix duplicate server names in generated profile links
- Update Cypress tests to validate correct URL behavior

**Does this PR introduce a breaking change?**
- No

# Checklist
- [x] Read, understood, and followed the contributing guidelines

### CODE REVIEW

File: components/AmbassadorsCard.tsx [hunk 1]
```diff
@@ -40,13 +40,25 @@ const getSocialMediaUrl = (
...
   };
-  return username ? baseUrls[platform] + username : undefined;
+
+  // Handle Mastodon handles in @username@server format
+  if (platform === 'mastodon') {
+    const mastodonMatch = username.match(/^@?([^@]+)@([^@]+)$/);
+    if (mastodonMatch) {
+      const [, user, server] = mastodonMatch;
+      return `https://${server}/@${user}`;
+    }
```
Comment (AgniveshChaubey) [inline components/AmbassadorsCard.tsx:58]: I think we can safely return `undefined` here if the mastodon username format doesnt match the regex

**Review by AgniveshChaubey — COMMENTED** [review]
Looks good to me. Just a small suggestion, then we can merge this

**Comment by me-pradeep** [comment]
@AgniveshChaubey I’ve made the suggested changes. Please take a look.

**Review by AgniveshChaubey — APPROVED** [review]

**Comment by AgniveshChaubey** [comment]
Thanks, merged!
