### PR TITLE
Removed Warnings 

### LINKED ISSUE #337: Several warnings errors in the console.
#### Describe the bug

In several files vs code terminal shows several warnings and errors 

#### How to Reproduce

Open the file, check problems section of vscode terminal

Screenshot from 2024-02-23 02-23-57

https://github.com/json-schema-org/website/

- [x] layout.tsx
- [x] [slug].page.tsx 

#### Expected behavior

There should be no console warnings and errors

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**GitHub Issue:** #337
closes #337
**Summary**:

Removed warnings from coming due to repetitive use of same tailwind classes in `[slug].page.tsx` file.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@benjagm pls. have a look

**Comment by Min2who** [comment]
> @benjagm pls. have a look

@DhairyaMajmudar thanks for your PR !!

Can you share the sc of the issue and as the pr is not linked to any issue it is hard to understand what you are trying to solve

**Comment by DhairyaMajmudar** [comment]
> > @benjagm pls. have a look
> 
> @DhairyaMajmudar thanks for your PR !!
> 
> Can you share the sc of the issue and as the pr is not linked to any issue it is hard to understand what you are trying to solve

I have opened an issue for that and updated the pr template.

**Comment by benjagm** [comment]
Thanks for the PR. Reviewing it right now!

File: components/Layout.tsx [hunk 1]
```diff
@@ -245,7 +245,7 @@ const Footer = () => (
             Slack</a>
         </div>
         <div className='mb-4 mr-4'>
-          <a href='https://twitter.com/jsonschema' className='flex items-center text-white'><img src='/img/logos/twitter_logo-white.svg' className='w-4 h-4 mr-2' />
+          <a href='https://twitter.com/jsonschema' className='flex items-center text-white'><img src='/img/logos/x-twitter.svg' className='w-4 h-4 mr-2' />
```
Comment (benjagm) [inline components/Layout.tsx:248]: Why changing the Twitter logo in this PR? I think is better to stick to the PR purpose and avoid adding additional unrelated features.

There is an issue for this: #331 and this will be managed in other PR.

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks a lot for this PR!!

Looks good. Just left a comment.

File: components/Layout.tsx (hunk 1 above)
Comment (DhairyaMajmudar) [reply components/Layout.tsx]: I have made the required changes in the PR : )

**Review by benjagm — APPROVED** [review]
Looks great! Nice job with this one!

**Comment by benjagm** [comment]
@DhairyaMajmudar can you please fix the conflicts? I'll merge this when is ready.

**Comment by DhairyaMajmudar** [comment]
@benjagm I have fixed the conflicts by updating my branch

**Comment by benjagm** [comment]
@DhairyaMajmudar I am going to merge this. Can you please take a look to the conflicts?
