### PR TITLE
fix: changed the code blocks (JsonEditor) to look light on light theme mode

### LINKED ISSUE #2127: 🐛 Bug: Code blocks remain dark in Light Theme mode
### Describe the bug

Code blocks in the JSON Schema documentation do not respect the user's theme preference. When the site is set to light theme mode, code blocks continue to display with dark backgrounds and light text, creating poor contrast and inconsistent user experience.

### Steps To Reproduce

1. Visit any documentation page with code blocks (e.g., "What is a schema?" page)
2. Switch to light theme using the theme toggle in the header
3. Observe that code blocks remain with dark backgrounds

### Expected Behavior

When the light theme is selected the code blocks should have light background.

### Screenshots

Current View: 

Image

Fixed View: 

Image

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by VIDIT45AGARWAL**
**What kind of change does this PR introduce?**

BugFix : Fixed light theme support for JSON editor and GettingStarted components

**Issue Number:**

Closes #2127 

**Screenshots/videos:**

Current View : 
Screenshot From 2026-01-18 20-47-16

Screenshot From 2026-01-21 00-29-21

Fixed View : 
Screenshot From 2026-01-18 20-47-23

Screenshot From 2026-01-21 00-29-06

**If relevant, did you update the documentation?**

No

**Summary**

This PR fixes light theme support for two key components:

**1)  JsonEditor Component:** 
Previously only supported dark theme styling. Now properly switches between light and dark themes with appropriate colors for text, backgrounds, borders, and syntax highlighting.

**2) GettingStarted Component:**
 Added full light theme support with proper color contrast, theme-aware syntax highlighting, and improved UI elements.

**3) Improved Test Stability:** 
Updated Cypress tests to use dedicated data-test attributes instead of theme-dependent CSS selectors. This prevents test failures during theme changes and makes tests more maintainable by separating styling concerns from test logic.

Key Changes:
1) Added useTheme hook to detect user's theme preference
2) Updated all color classes to include both light and dark variants (e.g., text-slate-800 dark:text-white)
3) Switched syntax highlighting between atomOneDark and atomOneLight based on theme
4) Fixed icon visibility in light mode with brightness adjustments
5) Cypress tests have been updated to use data-test attributes for reliable test selection

**Does this PR introduce a breaking change?**

No

# Checklist

Please ensure the following tasks are completed before submitting this pull request.

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by Utkarsh-123github — CHANGES_REQUESTED** [review]
Hi @VIDIT45AGARWAL , in your PR, tests are failing, please fix that.
Thanks!

**Comment by VIDIT45AGARWAL** [comment]
Hi @Utkarsh-123github , thanks for letting me know.
I’m currently figuring out how to resolve the failing tests. Please give me some time — I’ll update the PR once it’s fixed.

**Comment by VIDIT45AGARWAL** [comment]
Hey @Utkarsh-123github , now all checks have been passed. Please review the PR whenever you have a moment.
Thank You

**Comment by VIDIT45AGARWAL** [comment]
Also @Utkarsh-123github , if you are free please re-review this PR too.

**Comment by VIDIT45AGARWAL** [comment]
Hey @Utkarsh-123github , its been a while since the last update on this PR, whenever you are free could you please re-review it.
Thank You!

**Comment by VIDIT45AGARWAL** [comment]
any update on this @Utkarsh-123github ?

**Comment by VIDIT45AGARWAL** [comment]
Any updates @Utkarsh-123github ??

File: components/JsonEditor.tsx [hunk 1]
```diff
@@ -426,19 +429,31 @@ export default function JsonEditor({
...
+  const handleCopyClick = (textToCopy: string) => {
+    const text = String(textToCopy || '');
+    navigator.clipboard.writeText(text);
+    setCopied(true);
+    setTimeout(() => setCopied(false), 2000);
+  };
+
   // If not in JSON mode, render as regular code block
   if (!isJsonMode) {
+    const displayCode = (codeContent || ' ').trim() || ' ';
```
Comment (Utkarsh-123github) [inline components/JsonEditor.tsx:441]: Hi @VIDIT45AGARWAL 
Can you explain, why you added this change ?

**Review by Utkarsh-123github — CHANGES_REQUESTED** [review]

File: components/JsonEditor.tsx (hunk 1 above)
Comment (VIDIT45AGARWAL) [reply components/JsonEditor.tsx:441]: To ensure consistent rendering... empty code blocks need at least one character for react-syntax-highlighter to display line numbers and maintain proper layout.

Comment (VIDIT45AGARWAL) [reply components/JsonEditor.tsx]: To ensure consistent rendering... empty code blocks need at least one character for react-syntax-highlighter to display line numbers and maintain proper layout.

Comment (VIDIT45AGARWAL) [reply components/JsonEditor.tsx:441]: Any update @Utkarsh-123github ?

Comment (VIDIT45AGARWAL) [reply components/JsonEditor.tsx:441]: any updates @Utkarsh-123github  ?

**Comment by Utkarsh-123github** [comment]
Hi @VIDIT45AGARWAL 
The PR looks good to me.
Thanks for your patience.

@jagpreetrahi @vtushar06 any suggestions from your side ?

**Comment by jagpreetrahi** [comment]
Give me some time to go through it and will  update you if any  changes would require.

File: components/GettingStarted.tsx [hunk 2]
```diff
@@ -233,30 +257,34 @@ const GettingStarted = () => {
...
             </Highlight>
           </div>
-          <h2 className='text-h6 font-semibold'>Validation Result</h2>
-          <div className='flex bg-[#282c34] justify-between items-center text-white font-medium flex-row border p-5 rounded-xl'>
-            <p>{details[0]}</p>
+          <h2 className='text-h6 font-semibold text-slate-900 dark:text-white'>
+            Validation Result
+          </h2>
+          <div className='flex dark:bg-[#282c34] bg-slate-100 justify-between items-center text-slate-800 dark:text-white font-medium flex-row border dark:border-slate-700 border-slate-300 p-5 rounded-xl'>
+            <p className='text-slate-700 dark:text-slate-300'>{details[0]}</p>
```
Comment (jagpreetrahi) [inline components/GettingStarted.tsx:270]: hey @VIDIT45AGARWAL , this part of code does not make the consistent experience with both theme. The problem is as in light theme ,  i am not able to see the validation result status text properly with the image mainly for red cross image tick of results

File: components/GettingStarted.tsx [hunk 3]
```diff
@@ -233,30 +257,34 @@ const GettingStarted = () => {
...
+                className='dark:brightness-100 brightness-90'
               />
             ) : (
               <Image
                 src='/icons/red-cross.svg'
                 alt='red cross'
                 width={24}
                 height={24}
+                className='dark:brightness-100 brightness-90'
               />
```
Comment (jagpreetrahi) [inline components/GettingStarted.tsx:287]: try to give the more brightness of red cross for light theme

**Review by jagpreetrahi — COMMENTED** [review]
Hey @VIDIT45AGARWAL , thanks for working on it, but there are some changes that needs to fixing it. I am gonna attach the SS below , so that you can see them. The problem is that the validation results not looks as expected in light theme , it does not show the red-cross tick not properly and make in-consistent experience, however it works good in dark mode, but need to fix in light mode, apart from that currently, in the `create your schema` section there are two background color appears for the JSON editor in the dark theme, you can see on the bottom of the page.. This should be fixed so that we can have the consistent color for the editor instead of multiple ones.
Thanks

Image
Image
Image

**Comment by VIDIT45AGARWAL** [comment]
Sure @jagpreetrahi , I will do the requested changes and update you as soon as it is done.

**Comment by VIDIT45AGARWAL** [comment]
Hey @jagpreetrahi , is this much brightness fine ? I have also increased the brightness for compliant to schema box too a little.

Before:

image

After:

image


Also one more question, is there any changes need to be done in the last screenshot above?

**Comment by jagpreetrahi** [comment]
I think we can replicate the color for light theme  similar to dark them in the complaint msg bg instead of using red color right??

**Comment by jagpreetrahi** [comment]
And for the last ss , we need to have the same bg color for all examples used in editor  in dark theme

**Comment by VIDIT45AGARWAL** [comment]
> I think we can replicate the color for light theme similar to dark them in the complaint msg bg instead of using red color right??

In the dark mode the website is using red color only in the bg with 30% brightness so the same brightness in the light mode appears to be light, so i increased it to 80.

**Comment by VIDIT45AGARWAL** [comment]
> And for the last ss , we need to have the same bg color for all examples used in editor in dark theme

It was already like that only I didn't change anything for that block in the dark mode, but if you want I can change that too

**Comment by jagpreetrahi** [comment]
@VIDIT45AGARWAL , yesI  we need to change it @Utkarsh-123github what do u think on it?

**Comment by Utkarsh-123github** [comment]
Hi all, I think it would be great if you fix this.
Thanks!

**Comment by VIDIT45AGARWAL** [comment]
Hey @Utkarsh-123github @jagpreetrahi , I have made the requested changes. 

New View: 

image

**Comment by jagpreetrahi** [comment]
Nice lgtm

**Comment by Utkarsh-123github** [comment]
Thanks @jagpreetrahi for your detailed review.🚀
