### PR TITLE
Bug fix (Security Vulnerability)

### LINKED ISSUE #2227: 🐛 Bug: External link hardening needed: rel="noopener noreferrer" absent
### Describe the bug

Security Vulnerability: Tabnabbing Attack Risk
Issue:
Multiple external links use target="_blank" without proper security attributes (rel="noopener noreferrer"), exposing the site to potential tabnabbing attacks.

Affected Files:

pages/tools/components/ToolingTable.tsx
pages/tools/components/ToolingDetailModal.tsx
Impact:

Tabnabbing Attack: Malicious sites can access window.opener and redirect the original page to a phishing site
Privacy Leak: External sites receive Referer header information
Performance: New tabs run in the same process as the original page
Technical Details:
When a link opens with target="_blank" without rel="noopener", the newly opened page has access to window.opener, allowing it to execute:

window.opener.location = 'https://malicious-site.com/';

This can silently redirect the user's original tab to a phishing site that looks like the legitimate JSON Schema website.

### Steps To Reproduce

Navigate to the Tools page (/tools)
Click on any tool to open the detail modal
Inspect external links in the modal (Source, Homepage, Creator/Maintainer profiles, etc.)
Check browser DevTools Network tab - notice Referer header is sent
Open any external link in a new tab
In the new tab's console, check window.opener - it will reference the original page
A malicious site could use window.opener.location to redirect the original tab

Browser Support:
Modern browsers (Chrome 88+, Firefox, Safari) automatically apply noopener behavior, but explicit declaration is still recommended for:

Older browser support
Defense in depth
Code clarity and security intent
Compliance with security best practices

### Expected Behavior

All external links that open in new tabs (target="_blank") should include rel="noopener noreferrer" to:

Prevent Tabnabbing: Block window.opener access from the new page
Protect Privacy: Prevent Referer header from being sent to external sites
Improve Performance: Run new tabs in separate processes

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by Adityakk9031**
**What kind of change does this PR introduce?**

Bug fix – security hardening for external links by ensuring safe usage of `target="_blank"` with `rel="noopener noreferrer"` in tooling components.

**Issue Number**

Closes #2227

**Screenshots / Videos**

N/A – this is a code-level security fix with no visual changes expected.

**Summary**

This PR addresses the security vulnerability described in #2227 by adding `rel="noopener noreferrer"` to all external links in `ToolingTable.tsx` and `ToolingDetailModal.tsx`. It also corrects incorrect usages of `target="blank"` to the standard `target="_blank"` so that external links open in a new tab while following security best practices.

**Changes**

- Added `rel="noopener noreferrer"` to external `<a>` tags rendered in `ToolingTable.tsx`.
- Added `rel="noopener noreferrer"` to external `<a>` tags rendered in `ToolingDetailModal.tsx`.
- Replaced all occurrences of `target="blank"` with the correct `target="_blank"` value on external links.

**Does this PR introduce a breaking change?**

No.

**Documentation Updates**

N/A.

# Checklist

Please ensure the following tasks are completed before submitting this pull request.

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Adityakk9031** [comment]
ok i will fix the error later tomorrow

**Comment by Adityakk9031** [comment]
@jagpreetrahi hey please have a look

File: pages/tools/components/ToolingTable.tsx [hunk 1]
```diff
@@ -305,22 +306,19 @@ const ToolingTable = ({
...
+                              <a
+                                href={`https://bowtie.report/#/implementations/${bowtieData.id}`}
+                                target='_blank'
+                                rel='noopener noreferrer'
+                                onClick={(event) => event.stopPropagation()}
+                                title='See at Bowtie'
+                                className='ml-1'
+                              >
+                                <OutLinkIcon className='fill-none stroke-current w-5 h-5 stroke-2' />
+                              </a>
```
Comment (jagpreetrahi) [inline pages/tools/components/ToolingTable.tsx]: why you removed the `InfoIcon` from here?

File: pages/tools/components/ToolingTable.tsx [hunk 2]
```diff
@@ -305,22 +306,19 @@ const ToolingTable = ({
                         onClick={() => openModal(tool)}
                       >
                         <td className='p-2 relative'>
-                          {bowtieReport && (
```
Comment (Utkarsh-123github) [inline pages/tools/components/ToolingTable.tsx:308]: Hi @Adityakk9031 , Why you have made these changes ?

**Comment by Adityakk9031** [comment]
Hi @Utkarsh-123github, thanks for catching that!

In my previous commit, I accidentally removed the {bowtieData ? ... : <InfoIcon />} ternary logic in the mobile table section and replaced it with just the <a> tag. This would have broken the fallback — tools without Bowtie data would render a broken link instead of the info icon.

I've fixed this in my latest commit. The changes are now minimal and purely security-focused:

Fixed target='blank' → target='_blank' (typo in original code)
Added rel='noopener noreferrer' to all external links
No structural or behavioral changes — the ternary fallback with InfoIcon is fully preserved
Could you please re-review? Thanks!

File: pages/tools/components/ToolingTable.tsx (hunk 1 above)
Comment (Adityakk9031) [reply pages/tools/components/ToolingTable.tsx]: Hi @jagpreetrahi, that was a mistake in my earlier commit — I accidentally removed the InfoIcon fallback. I've since fixed it in my latest commits (ca12ca4 and 9c808e6). The {bowtieData ? <a>... : <InfoIcon>} ternary is now fully restored. The changes are now purely target='blank' → target='_blank' + rel='noopener noreferrer' with no structural changes. Thanks for the approval!

**Comment by Adityakk9031** [comment]
@jagpreetrahi please merge this pr and this one https://github.com/json-schema-org/website/pull/2236

**Comment by Utkarsh-123github** [comment]
LGTM🚀
Thanks @Adityakk9031 for your efforts and contribution!
