### PR TITLE
Fix/select dropdown arrow v3

### LINKED ISSUE #2309: 🐛 Bug: Dropdown Arrow Flush Against Right Edge
### Describe the bug

The arrow/chevron icon of the "Select a Schema" dropdown is visually attached to the right edge of the dropdown with no padding or spacing. This makes the UI look unpolished and inconsistent with standard dropdown styling conventions.

### Steps To Reproduce

1. Navigate to the "Get Started > Create your first schema" page
2. Observe the "Select a Schema" dropdown in the JSON Schema section

### Expected Behavior

The dropdown arrow should have adequate right-side padding/spacing so it doesn't appear flush against the border.

**Actual Behavior:**
The arrow icon is stuck to the far right edge of the dropdown with no visible padding.

**Suggested Fix:**
Add `padding-right` to the `<select>` element or its wrapper to give the arrow icon breathing room. For example:
```css
select {
  padding-right: 2rem;
}
```

### Screenshots

Image

### Device Information [optional]

```markdown
- OS:MacOS
- Browser:Chrome
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by Tushar8466**
**What kind of change does this PR introduce?**
Bug fix - replaced native browser dropdown arrow with a custom styled arrow for better cross-browser consistency and improved spacing.

fixes #2309 

# Checklist
- [x] I have read the contributing guidelines
- [x] My changes are consistent with the project's coding style
- [x] I have tested my changes locally

### CODE REVIEW

**Comment by Utkarsh-123github** [comment]
Hi @Tushar8466 
Please add a good detailed description of your changes. 
Also if possible, then please add recordings/screenshots before and after changes. This gives a better clarity of your approach and solution.
Thanks!

**Comment by Tushar8466** [comment]
## Before
Screenshot 2026-03-10 at 1 52 38 PM




## After
Screenshot 2026-03-10 at 1 55 01 PM

**Comment by Tushar8466** [comment]
**What kind of change does this PR introduce?**
Bug fix - replaced the native browser dropdown arrow in the Getting Started page select elements with a custom styled arrow to fix inconsistent spacing and appearance across different browsers.

fixes #2329 

**What is the current behavior?**
The native browser dropdown arrow appears flush against the right edge of the select elements with no margin, causing poor visual appearance. The arrow styling also varies across different browsers, leading to inconsistent UX.

**What is the new behavior?**
- Native browser arrow is hidden using `appearance-none`
- A custom styled `▾` arrow is added with proper spacing using absolute positioning
- Added `pr-8` padding to prevent text from overlapping the custom arrow
- Both Schema and Instance select dropdowns are updated consistently
- Unique IDs (`schema-examples` and `instance-examples`) are added to select elements to fix duplicate ID accessibility issue
- Labels are properly linked to their select elements using `htmlFor`

# Checklist
- [x] I have read the contributing guidelines
- [x] My changes are consistent with the project's coding style
- [x] I have tested my changes locally

**Comment by Tushar8466** [comment]
@Utkarsh-123github I have updated the PR description with detailed information including the current behavior, new behavior, all changes made, and before/after comparison. I have also added before and after screenshots to visually demonstrate the fix. Please review when you get a chance. Thanks!

File: components/GettingStarted.tsx [hunk 1]
```diff
@@ -203,26 +211,34 @@ const GettingStarted = () => {
...
+                  onChange={handleInstanceChange}
+                >
+                  {instances.map((instance: any, id: number) => (
+                    <option key={id} value={instance.file}>
+                      {instance.name}
+                    </option>
+                  ))}
+                </select>
+                <span className='pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 dark:text-slate-300 text-xl'>
+                  ▾
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx]: We already use Chevron Down and Chevron Up icons from Lucide-react in our codebase. Please use that instead of manually adding symbol.

File: components/GettingStarted.tsx [hunk 2]
```diff
@@ -139,26 +139,34 @@ const GettingStarted = () => {
...
+                  onChange={handleSchemaChange}
+                >
+                  {options.map((option: any, id: number) => (
+                    <option key={id} value={option.file}>
+                      {option.name}
+                    </option>
+                  ))}
+                </select>
+                <span className='pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 dark:text-slate-300 text-xl'>
+                  ▾
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx]: We already use Chevron Down and Chevron Up icons from Lucide-react in our codebase. Please use that instead of manually adding symbol.

**Review by Utkarsh-123github — CHANGES_REQUESTED** [review]

**Comment by Tushar8466** [comment]
@Utkarsh-123github I’ve made the requested changes. Replaced the dropdown arrow with Chevron icons from lucide-react and adjusted the spacing for better alignment. Please review.

File: components/GettingStarted.tsx [hunk 3]
```diff
@@ -250,40 +251,31 @@ const GettingStarted = () => {
               style={resolvedTheme === 'dark' ? atomOneDark : atomOneLight}
               showLineNumbers
               startingLineNumber={1}
-              lineProps={() => {
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx:253]: How this change is related to your PR?

File: components/GettingStarted.tsx [hunk 4]
```diff
@@ -250,40 +251,31 @@ const GettingStarted = () => {
...
               {JSON.stringify(fetchedInstance, null, 2)}
             </Highlight>
           </div>
+
           <h2 className='text-h6 font-semibold text-slate-900 dark:text-white'>
             Validation Result
           </h2>
+
           <div className='flex dark:bg-[#1e293b] bg-slate-100 justify-between items-center text-slate-800 dark:text-white font-medium flex-row border dark:border-slate-700 border-slate-300 p-5 rounded-xl'>
-            <p className='text-slate-700 dark:text-slate-300'>{details[0]}</p>
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx:270]: Why this change ?

File: components/GettingStarted.tsx [hunk 5]
```diff
@@ -186,45 +193,39 @@ const GettingStarted = () => {
               }}
               style={resolvedTheme === 'dark' ? atomOneDark : atomOneLight}
               showLineNumbers
-              startingLineNumber={1}
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx:189]: Why this change ?

File: components/GettingStarted.tsx [hunk 6]
```diff
@@ -143,29 +144,35 @@ const GettingStarted = () => {
...
+                </select>
+
+                <ChevronDown className='w-4 h-4 text-gray-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none' />
+              </div>
             </div>
           </div>
 
           <div className='overflow-x-auto flex-basis-0 max-w-full min-w-0 shrink lg:max-w-[800px] xl:max-w-[900px]'>
             <Highlight
-              wrapLines={true}
```
Comment (Utkarsh-123github) [inline components/GettingStarted.tsx:167]: Why this change ?

**Review by Utkarsh-123github — CHANGES_REQUESTED** [review]

**Comment by Utkarsh-123github** [comment]
Hi @Tushar8466 
Please add only those changes that are required to resolve your issue.

**Comment by Tushar8466** [comment]
Hey @Utkarsh-123github, sorry for the confusion here! 🙏

I didn't intend to include those changes in this PR. I was working on resolving a separate issue, and somehow those changes got bundled in unintentionally.

**Review by Utkarsh-123github — APPROVED** [review]
LGTM
Thanks @Tushar8466 for your efforts and contribution.
